# Generated by Django 4.2.7 on 2025-11-15 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('PAGE_VIEW', 'Page View'), ('RESTAURANT_VIEW', 'Restaurant View'), ('MENU_VIEW', 'Menu View'), ('ADD_TO_CART', 'Add to Cart'), ('REMOVE_FROM_CART', 'Remove from Cart'), ('CHECKOUT_START', 'Checkout Started'), ('ORDER_PLACED', 'Order Placed'), ('SEARCH', 'Search'), ('FILTER_APPLIED', 'Filter Applied')], max_length=50)),
                ('properties', models.JSONField(default=dict)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_events',
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='analytics_e_event_t_c3dcde_idx'), models.Index(fields=['user'], name='analytics_e_user_id_f525be_idx'), models.Index(fields=['session_id'], name='analytics_e_session_b3cbf5_idx'), models.Index(fields=['created_at'], name='analytics_e_created_3bce1d_idx')],
            },
        ),
    ]
