# Generated by Django 4.2.7 on 2025-11-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='last_auto_disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
