# Generated by Django 4.2.7 on 2025-11-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='offer_sound_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='push_delivery_offers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='push_shift_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='push_surge_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='snooze_mode_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='snooze_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='sound_alerts_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='surge_sound_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ORDER_PLACED', 'Order Placed'), ('ORDER_ACCEPTED', 'Order Accepted'), ('ORDER_READY', 'Order Ready'), ('ORDER_OUT_FOR_DELIVERY', 'Out for Delivery'), ('ORDER_DELIVERED', 'Order Delivered'), ('ORDER_CANCELLED', 'Order Cancelled'), ('PAYMENT_SUCCESS', 'Payment Successful'), ('PAYMENT_FAILED', 'Payment Failed'), ('PROMOTION', 'Promotion'), ('REVIEW_REQUEST', 'Review Request'), ('SYSTEM', 'System Notification'), ('DELIVERY_OFFER', 'New Delivery Offer'), ('DELIVERY_OFFER_EXPIRED', 'Delivery Offer Expired'), ('DELIVERY_CANCELLED', 'Delivery Cancelled'), ('SHIFT_REMINDER', 'Shift Reminder'), ('SURGE_ALERT', 'Surge Pricing Alert'), ('EARNINGS_PAYOUT', 'Earnings Payout'), ('DOCUMENT_EXPIRY', 'Document Expiry Reminder'), ('HIGH_PRIORITY_ALERT', 'High Priority Alert')], max_length=50),
        ),
    ]
