# Generated by Django 4.2.7 on 2025-11-15 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('pickup_address', models.TextField()),
                ('pickup_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delivery_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delivery_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Assignment'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted by Rider'), ('REJECTED', 'Rejected by Rider'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('estimated_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('actual_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('base_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('distance_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tip_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('failure_reason', models.TextField(blank=True)),
                ('failure_code', models.CharField(blank=True, max_length=50)),
                ('is_contactless', models.BooleanField(default=False)),
                ('delivery_photo', models.ImageField(blank=True, null=True, upload_to='deliveries/photos/')),
                ('delivery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order')),
                ('rider', models.ForeignKey(blank=True, limit_choices_to={'role': 'DELIVERY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deliveries',
            },
        ),
        migrations.CreateModel(
            name='RiderLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('rider', models.ForeignKey(limit_choices_to={'role': 'DELIVERY'}, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rider_locations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rider', '-created_at'], name='rider_locat_rider_i_9a8507_idx'), models.Index(fields=['-created_at'], name='rider_locat_created_7c86d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiderEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('distance_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tip_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payout_period_start', models.DateField()),
                ('payout_period_end', models.DateField()),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='deliveries.delivery')),
                ('rider', models.ForeignKey(limit_choices_to={'role': 'DELIVERY'}, on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rider_earnings',
                'indexes': [models.Index(fields=['rider', 'is_paid'], name='rider_earni_rider_i_9dea16_idx'), models.Index(fields=['payout_period_start', 'payout_period_end'], name='rider_earni_payout__9a5b08_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('document_type', models.CharField(choices=[('LICENSE', 'Driver License'), ('INSURANCE', 'Insurance'), ('VEHICLE_REGISTRATION', 'Vehicle Registration'), ('BACKGROUND_CHECK', 'Background Check'), ('OTHER', 'Other')], max_length=50)),
                ('document_file', models.FileField(upload_to='deliveries/documents/')),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('rider', models.ForeignKey(limit_choices_to={'role': 'DELIVERY'}, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'delivery_documents',
                'indexes': [models.Index(fields=['rider', 'is_verified'], name='delivery_do_rider_i_ed5666_idx'), models.Index(fields=['document_type'], name='delivery_do_documen_26a0a5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['rider', 'status'], name='deliveries_rider_i_896609_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['order'], name='deliveries_order_i_744a2b_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status'], name='deliveries_status_c2a7cc_idx'),
        ),
    ]
