# Generated by Django 4.2.7 on 2025-11-17 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deliveries', '0002_fleet_riderwallet_alter_delivery_status_ridershift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='delivery',
            name='customer_phone_masked',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_otp',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='delivery',
            name='estimated_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='estimated_travel_time_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delivery',
            name='live_eta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pause_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='delivery',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='restaurant_phone_masked',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='delivery',
            name='resumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='route_preview_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='delivery',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='deliveries/signatures/'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='unable_to_deliver_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='delivery',
            name='unable_to_deliver_photo',
            field=models.ImageField(blank=True, null=True, upload_to='deliveries/unable_to_deliver/'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='unable_to_deliver_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='riderlocation',
            name='battery_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderlocation',
            name='drop_zone_entered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderlocation',
            name='is_moving',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riderlocation',
            name='is_offline_sync',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riderlocation',
            name='location_mode',
            field=models.CharField(default='BALANCED', max_length=20),
        ),
        migrations.AddField(
            model_name='riderlocation',
            name='near_drop_zone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riderlocation',
            name='near_pickup_zone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riderlocation',
            name='offline_queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderlocation',
            name='pickup_zone_entered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TripLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_distance_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_time_minutes', models.IntegerField(default=0)),
                ('idle_time_minutes', models.IntegerField(default=0)),
                ('trip_started_at', models.DateTimeField()),
                ('trip_ended_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_arrived_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_completed_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_arrived_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_completed_at', models.DateTimeField(blank=True, null=True)),
                ('base_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('distance_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('time_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('tip_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('route_taken', models.JSONField(default=list)),
                ('route_efficiency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_logs', to='deliveries.delivery')),
                ('rider', models.ForeignKey(limit_choices_to={'role': 'DELIVERY'}, on_delete=django.db.models.deletion.CASCADE, related_name='trip_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trip_logs',
                'ordering': ['-trip_started_at'],
                'indexes': [models.Index(fields=['rider', '-trip_started_at'], name='trip_logs_rider_i_e2b648_idx'), models.Index(fields=['delivery'], name='trip_logs_deliver_301da4_idx'), models.Index(fields=['trip_started_at'], name='trip_logs_trip_st_d3fae9_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_tracking_enabled', models.BooleanField(default=True)),
                ('location_mode', models.CharField(default='BALANCED', max_length=20)),
                ('location_update_interval_moving', models.IntegerField(default=5)),
                ('location_update_interval_idle', models.IntegerField(default=30)),
                ('share_location_during_shift_only', models.BooleanField(default=True)),
                ('push_notifications_enabled', models.BooleanField(default=True)),
                ('sound_alerts_enabled', models.BooleanField(default=True)),
                ('offer_sound_enabled', models.BooleanField(default=True)),
                ('snooze_mode_enabled', models.BooleanField(default=False)),
                ('snooze_until', models.DateTimeField(blank=True, null=True)),
                ('preferred_navigation_app', models.CharField(default='GOOGLE_MAPS', max_length=50)),
                ('auto_accept_enabled', models.BooleanField(default=False)),
                ('location_privacy_enabled', models.BooleanField(default=True)),
                ('rider', models.OneToOneField(limit_choices_to={'role': 'DELIVERY'}, on_delete=django.db.models.deletion.CASCADE, related_name='rider_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rider_settings',
                'indexes': [models.Index(fields=['rider'], name='rider_setti_rider_i_7ede0b_idx')],
            },
        ),
        migrations.CreateModel(
            name='OfflineAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('ACCEPT_OFFER', 'Accept Offer'), ('DECLINE_OFFER', 'Decline Offer'), ('COMPLETE_DELIVERY', 'Complete Delivery'), ('UPDATE_LOCATION', 'Update Location'), ('PAUSE_TRIP', 'Pause Trip'), ('RESUME_TRIP', 'Resume Trip')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCING', 'Syncing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('action_data', models.JSONField(default=dict)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=5)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True)),
                ('rider', models.ForeignKey(limit_choices_to={'role': 'DELIVERY'}, on_delete=django.db.models.deletion.CASCADE, related_name='offline_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offline_actions',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['rider', 'status'], name='offline_act_rider_i_05c06e_idx'), models.Index(fields=['status', 'next_retry_at'], name='offline_act_status_7ea2e0_idx'), models.Index(fields=['action_type', 'status'], name='offline_act_action__99ad14_idx')],
            },
        ),
    ]
