# Generated by Django 4.2.7 on 2025-11-17 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deliveries', '0003_delivery_customer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLETAPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ml_predicted_eta_minutes', models.IntegerField(blank=True, null=True)),
                ('ml_predicted_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('actual_eta_minutes', models.IntegerField(blank=True, null=True)),
                ('actual_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('traffic_conditions', models.CharField(blank=True, max_length=50)),
                ('weather_conditions', models.CharField(blank=True, max_length=50)),
                ('time_of_day', models.TimeField(blank=True, null=True)),
                ('day_of_week', models.IntegerField(blank=True, null=True)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('prediction_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ml_eta_predictions',
            },
        ),
        migrations.CreateModel(
            name='MultiTenantFleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('organization_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('max_riders', models.IntegerField(blank=True, default=100, null=True)),
                ('custom_branding_enabled', models.BooleanField(default=False)),
                ('logo_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(blank=True, max_length=7)),
                ('secondary_color', models.CharField(blank=True, max_length=7)),
                ('custom_settings', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'multi_tenant_fleets',
            },
        ),
        migrations.CreateModel(
            name='VoiceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('command_type', models.CharField(choices=[('ACCEPT_OFFER', 'Accept Offer'), ('DECLINE_OFFER', 'Decline Offer'), ('START_SHIFT', 'Start Shift'), ('END_SHIFT', 'End Shift'), ('PAUSE_TRIP', 'Pause Trip'), ('RESUME_TRIP', 'Resume Trip'), ('NAVIGATE', 'Navigate'), ('CALL_CUSTOMER', 'Call Customer'), ('CALL_RESTAURANT', 'Call Restaurant'), ('SOS', 'Emergency SOS'), ('OTHER', 'Other')], max_length=50)),
                ('spoken_text', models.TextField()),
                ('recognized_text', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('accuracy_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('audio_file_url', models.URLField(blank=True, null=True)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveries.delivery')),
                ('rider', models.ForeignKey(limit_choices_to={'role': 'DELIVERY'}, on_delete=django.db.models.deletion.CASCADE, related_name='voice_commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voice_commands',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('rider', models.ForeignKey(limit_choices_to={'role': 'DELIVERY'}, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_associations', to=settings.AUTH_USER_MODEL)),
                ('tenant_fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_riders', to='deliveries.multitenantfleet')),
            ],
            options={
                'db_table': 'tenant_riders',
            },
        ),
        migrations.CreateModel(
            name='RiderLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=1)),
                ('total_points', models.IntegerField(default=0)),
                ('current_level_points', models.IntegerField(default=0)),
                ('points_needed_for_next_level', models.IntegerField(default=100)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_distance_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_level_up_at', models.DateTimeField(blank=True, null=True)),
                ('rider', models.OneToOneField(limit_choices_to={'role': 'DELIVERY'}, on_delete=django.db.models.deletion.CASCADE, related_name='rider_level', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rider_levels',
            },
        ),
        migrations.CreateModel(
            name='RiderAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('achievement_type', models.CharField(choices=[('FIRST_DELIVERY', 'First Delivery'), ('COMPLETE_10', 'Complete 10 Deliveries'), ('COMPLETE_50', 'Complete 50 Deliveries'), ('COMPLETE_100', 'Complete 100 Deliveries'), ('COMPLETE_500', 'Complete 500 Deliveries'), ('PERFECT_RATING', 'Perfect 5-Star Rating'), ('FAST_DELIVERY', 'Fast Delivery'), ('NIGHT_OWL', 'Night Owl'), ('EARLY_BIRD', 'Early Bird'), ('WEEKEND_WARRIOR', 'Weekend Warrior'), ('STREAK_7', '7 Day Streak'), ('STREAK_30', '30 Day Streak'), ('MILEAGE_MILESTONE', 'Mileage Milestone')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon_url', models.URLField(blank=True)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('rider', models.ForeignKey(limit_choices_to={'role': 'DELIVERY'}, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rider_achievements',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='multitenantfleet',
            index=models.Index(fields=['organization_code'], name='multi_tenan_organiz_20477e_idx'),
        ),
        migrations.AddIndex(
            model_name='multitenantfleet',
            index=models.Index(fields=['is_active'], name='multi_tenan_is_acti_861027_idx'),
        ),
        migrations.AddField(
            model_name='mletaprediction',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eta_predictions', to='deliveries.delivery'),
        ),
        migrations.AddField(
            model_name='mletaprediction',
            name='rider',
            field=models.ForeignKey(limit_choices_to={'role': 'DELIVERY'}, on_delete=django.db.models.deletion.CASCADE, related_name='eta_predictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='voicecommand',
            index=models.Index(fields=['rider', '-created_at'], name='voice_comma_rider_i_3b7da9_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecommand',
            index=models.Index(fields=['command_type', 'status'], name='voice_comma_command_784912_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecommand',
            index=models.Index(fields=['status'], name='voice_comma_status_e73791_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantrider',
            index=models.Index(fields=['tenant_fleet', 'rider'], name='tenant_ride_tenant__fde2d2_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantrider',
            index=models.Index(fields=['tenant_fleet', 'is_active'], name='tenant_ride_tenant__4c5ad0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantrider',
            unique_together={('tenant_fleet', 'rider')},
        ),
        migrations.AddIndex(
            model_name='riderlevel',
            index=models.Index(fields=['rider'], name='rider_level_rider_i_9f96da_idx'),
        ),
        migrations.AddIndex(
            model_name='riderlevel',
            index=models.Index(fields=['level', '-total_points'], name='rider_level_level_b08abe_idx'),
        ),
        migrations.AddIndex(
            model_name='riderachievement',
            index=models.Index(fields=['rider', '-earned_at'], name='rider_achie_rider_i_204257_idx'),
        ),
        migrations.AddIndex(
            model_name='riderachievement',
            index=models.Index(fields=['achievement_type'], name='rider_achie_achieve_0212c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='riderachievement',
            unique_together={('rider', 'achievement_type')},
        ),
        migrations.AddIndex(
            model_name='mletaprediction',
            index=models.Index(fields=['delivery', 'rider'], name='ml_eta_pred_deliver_940e51_idx'),
        ),
        migrations.AddIndex(
            model_name='mletaprediction',
            index=models.Index(fields=['prediction_timestamp'], name='ml_eta_pred_predict_12d719_idx'),
        ),
        migrations.AddIndex(
            model_name='mletaprediction',
            index=models.Index(fields=['confidence_score'], name='ml_eta_pred_confide_a4da14_idx'),
        ),
    ]
