# Generated by Django 4.2.7 on 2025-11-16 17:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0002_menuitem_image_url_restaurant_hero_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.CharField(max_length=255, unique=True)),
                ('search_count', models.IntegerField(default=1)),
                ('last_searched', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'popular_searches',
                'ordering': ['-search_count'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.CharField(max_length=255)),
                ('search_type', models.CharField(default='general', max_length=50)),
            ],
            options={
                'db_table': 'search_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='allergens',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='macros',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='promotion',
            name='applicable_banks',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='promotion',
            name='applicable_upi_providers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='promotion',
            name='cashback_max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='cashback_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='offer_type',
            field=models.CharField(choices=[('RESTAURANT', 'Restaurant Offer'), ('PLATFORM', 'Platform Offer'), ('BANK', 'Bank Offer'), ('UPI', 'UPI Offer')], default='RESTAURANT', max_length=20),
        ),
        migrations.AddField(
            model_name='promotion',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cost_for_two',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='has_offers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='hygiene_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_halal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_pure_veg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount'), ('BUY_ONE_GET_ONE', 'Buy One Get One'), ('FREE_DELIVERY', 'Free Delivery'), ('CASHBACK', 'Cashback')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['offer_type', 'is_active'], name='promotions_offer_t_d15ebd_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['priority'], name='promotions_priorit_31fc0e_idx'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='popularsearch',
            index=models.Index(fields=['-search_count'], name='popular_sea_search__b72fa3_idx'),
        ),
        migrations.AddIndex(
            model_name='popularsearch',
            index=models.Index(fields=['-last_searched'], name='popular_sea_last_se_deb4c6_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user', '-created_at'], name='search_hist_user_id_3ea0ad_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['query'], name='search_hist_query_69a772_idx'),
        ),
    ]
