# Generated by Django 4.2.7 on 2025-11-16 20:00

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0003_popularsearch_searchhistory_menuitem_allergens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_before', models.CharField(blank=True, max_length=20)),
                ('status_after', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'restaurant_document_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('GENERAL_MANAGER', 'General Manager'), ('KITCHEN_MANAGER', 'Kitchen Manager'), ('OPERATIONS', 'Operations Manager'), ('FINANCE', 'Finance Manager'), ('STAFF', 'Staff')], default='GENERAL_MANAGER', max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('permissions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
            ],
            options={
                'db_table': 'restaurant_managers',
            },
        ),
        migrations.CreateModel(
            name='RestaurantBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('branch_code', models.CharField(blank=True, max_length=50)),
                ('branch_type', models.CharField(choices=[('MAIN', 'Main Kitchen'), ('CLOUD', 'Cloud Kitchen'), ('BILLING', 'Billing Office'), ('PICKUP', 'Pickup Counter'), ('DINE_IN', 'Dine-in Outlet')], default='MAIN', max_length=20)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='India', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('service_radius_km', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('supports_delivery', models.BooleanField(default=True)),
                ('supports_pickup', models.BooleanField(default=True)),
                ('supports_dine_in', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'restaurant_branches',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('document_type', models.CharField(choices=[('PAN', 'PAN Card'), ('GST', 'GST Certificate'), ('FSSAI', 'FSSAI License'), ('BANK', 'Bank Statement'), ('CANCELLED_CHEQUE', 'Cancelled Cheque'), ('MENU', 'Menu Document'), ('OTHER', 'Other')], max_length=30)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(upload_to='restaurants/kyc/documents/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('needs_reupload', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'restaurant_documents',
            },
        ),
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('default_prep_time_minutes', models.IntegerField(default=20)),
                ('max_delivery_distance_km', models.DecimalField(decimal_places=2, default=8.0, max_digits=5)),
                ('auto_accept_orders', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('order_notifications', models.JSONField(default=dict)),
                ('sla_threshold_minutes', models.IntegerField(default=35)),
                ('kitchen_notes', models.TextField(blank=True)),
                ('packaging_instructions', models.TextField(blank=True)),
                ('supports_dine_in', models.BooleanField(default=False)),
                ('supports_takeaway', models.BooleanField(default=True)),
                ('supports_delivery', models.BooleanField(default=True)),
                ('delivery_radius_settings', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'restaurant_settings',
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='billing_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='billing_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='billing_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='billing_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='billing_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ITALIAN', 'Italian'), ('CHINESE', 'Chinese'), ('INDIAN', 'Indian'), ('MEXICAN', 'Mexican'), ('JAPANESE', 'Japanese'), ('AMERICAN', 'American'), ('THAI', 'Thai'), ('MEDITERRANEAN', 'Mediterranean'), ('FAST_FOOD', 'Fast Food'), ('VEGETARIAN', 'Vegetarian'), ('VEGAN', 'Vegan'), ('OTHER', 'Other')], max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_radius_km',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='estimated_preparation_time',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='fssai_license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_multi_branch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='manager_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='manager_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='manager_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='onboarding_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted for Review'), ('APPROVED', 'Approved'), ('REVISIONS_REQUIRED', 'Revisions Required')], default='NOT_STARTED', max_length=30),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('VEG', 'Vegetarian'), ('NON_VEG', 'Non-Vegetarian'), ('PURE_VEG', 'Pure Vegetarian')], default='NON_VEG', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='support_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['restaurant_type'], name='restaurants_restaur_87ae9f_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['onboarding_status'], name='restaurants_onboard_4f4ef6_idx'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='restaurantdocument',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='restaurants.restaurantbranch'),
        ),
        migrations.AddField(
            model_name='restaurantdocument',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='restaurantbranch',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_restaurants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentreviewlog',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='restaurants.restaurantdocument'),
        ),
        migrations.AddField(
            model_name='documentreviewlog',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='restaurantsettings',
            index=models.Index(fields=['restaurant'], name='restaurant__restaur_da9187_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantsettings',
            index=models.Index(fields=['is_online'], name='restaurant__is_onli_57f4f4_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantdocument',
            index=models.Index(fields=['restaurant', 'document_type'], name='restaurant__restaur_ec6111_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantdocument',
            index=models.Index(fields=['status'], name='restaurant__status_f4ab5e_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantbranch',
            index=models.Index(fields=['restaurant', 'branch_type'], name='restaurant__restaur_5c9f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantbranch',
            index=models.Index(fields=['city', 'state'], name='restaurant__city_e026b9_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantbranch',
            index=models.Index(fields=['is_primary'], name='restaurant__is_prim_b96180_idx'),
        ),
        migrations.AddIndex(
            model_name='managerprofile',
            index=models.Index(fields=['restaurant', 'role'], name='restaurant__restaur_0b8797_idx'),
        ),
        migrations.AddIndex(
            model_name='managerprofile',
            index=models.Index(fields=['email'], name='restaurant__email_7a0637_idx'),
        ),
        migrations.AddIndex(
            model_name='managerprofile',
            index=models.Index(fields=['is_primary'], name='restaurant__is_prim_c63a5f_idx'),
        ),
    ]
