# Generated by Django 4.2.7 on 2025-11-16 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_combined_parent_order_internal_cooking_notes_and_more'),
        ('restaurants', '0004_documentreviewlog_managerprofile_restaurantbranch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('alert_type', models.CharField(choices=[('SLA_BREACH', 'SLA Breach'), ('INVENTORY_LOW', 'Low Inventory'), ('NEW_REVIEW', 'New Review'), ('PAYOUT', 'Payout'), ('REFUND_SPIKE', 'Refund Spike'), ('SYSTEM', 'System Alert')], default='SYSTEM', max_length=30)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='orders.order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'restaurant_alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant', 'alert_type'], name='restaurant__restaur_9edd19_idx'), models.Index(fields=['restaurant', 'is_read'], name='restaurant__restaur_f83e72_idx'), models.Index(fields=['severity'], name='restaurant__severit_008cf6_idx')],
            },
        ),
    ]
