# Generated by Django 4.2.7 on 2025-11-18 10:19

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(db_index=True, max_length=100)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('aggregate_type', models.CharField(db_index=True, max_length=100)),
                ('aggregate_id', models.CharField(db_index=True, max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sequence_number', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['sequence_number'],
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['aggregate_type', 'aggregate_id', 'timestamp'], name='events_aggrega_1dbce6_btree'), django.contrib.postgres.indexes.BTreeIndex(fields=['type', 'timestamp'], name='events_type_037eb4_btree'), django.contrib.postgres.indexes.BTreeIndex(fields=['timestamp'], name='events_timesta_ec6861_btree'), django.contrib.postgres.indexes.BTreeIndex(fields=['sequence_number'], name='events_sequenc_3d7f53_btree')],
            },
        ),
    ]
