# Generated by Django 4.2.7 on 2025-11-16 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_contactless_delivery_order_courier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='combined_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combined_children', to='orders.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='internal_cooking_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kitchen_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='prep_time_override_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='print_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='priority_tag',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('RUSH', 'Rush'), ('VIP', 'VIP')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='sla_breach_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='sla_breached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['restaurant', 'priority_tag'], name='orders_restaur_a3d52a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['sla_breached'], name='orders_sla_bre_dd3c31_idx'),
        ),
    ]
