# Generated by Django 4.2.7 on 2025-11-17 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_apple_id_user_auth_provider_user_facebook_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biometric_type', models.CharField(choices=[('FINGERPRINT', 'Fingerprint'), ('FACE_ID', 'Face ID'), ('VOICE', 'Voice Recognition'), ('IRIS', 'Iris Scan'), ('PALM', 'Palm Print')], max_length=20)),
                ('biometric_id', models.CharField(max_length=255, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('public_key_hash', models.CharField(blank=True, max_length=255)),
                ('challenge_expires_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biometric_auths', to='accounts.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_auths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'biometric_auths',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refresh_token_jti', models.CharField(db_index=True, max_length=255, unique=True)),
                ('access_token_hash', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('LOGGED_OUT', 'Logged Out')], default='ACTIVE', max_length=20)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('login_method', models.CharField(default='PASSWORD', max_length=50)),
                ('biometric_auth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.biometricauth')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='accounts.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_sessions',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', 'status'], name='user_sessio_user_id_b0c39f_idx'), models.Index(fields=['device', 'status'], name='user_sessio_device__39ab62_idx'), models.Index(fields=['refresh_token_jti'], name='user_sessio_refresh_aecb8e_idx'), models.Index(fields=['last_activity'], name='user_sessio_last_ac_7cb421_idx'), models.Index(fields=['expires_at'], name='user_sessio_expires_66ae96_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='biometricauth',
            index=models.Index(fields=['user', 'is_enabled'], name='biometric_a_user_id_52c228_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricauth',
            index=models.Index(fields=['device', 'biometric_type'], name='biometric_a_device__68a683_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricauth',
            index=models.Index(fields=['biometric_id'], name='biometric_a_biometr_718683_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='biometricauth',
            unique_together={('user', 'device', 'biometric_type')},
        ),
    ]
