# Generated by Django 4.2.7 on 2025-11-17 05:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_combined_parent_order_internal_cooking_notes_and_more'),
        ('payments', '0003_settlementcycle_reconciliationreport_payout_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_panel', '0003_scheduledjob_webhook_webhookdelivery_jobexecution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('rollout_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('target_audience', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feature_flags',
            },
        ),
        migrations.CreateModel(
            name='FraudDetectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(max_length=50)),
                ('conditions', models.JSONField(default=dict)),
                ('action', models.CharField(max_length=50)),
                ('risk_score_threshold', models.IntegerField(default=70)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fraud_detection_rules',
            },
        ),
        migrations.CreateModel(
            name='SLO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_name', models.CharField(max_length=100)),
                ('metric_name', models.CharField(max_length=100)),
                ('target_value', models.FloatField()),
                ('current_value', models.FloatField(blank=True, null=True)),
                ('window_days', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'slos',
                'unique_together': {('service_name', 'metric_name')},
            },
        ),
        migrations.CreateModel(
            name='IPBlacklistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fraud_ip_blacklist',
            },
        ),
        migrations.CreateModel(
            name='FraudFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('risk_score', models.IntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fraud_flags', to=settings.AUTH_USER_MODEL)),
                ('rule_triggered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.frauddetectionrule')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fraud_flags',
                'ordering': ['-risk_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlagHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('before_state', models.JSONField(default=dict)),
                ('after_state', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='admin_panel.featureflag')),
            ],
            options={
                'db_table': 'feature_flag_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chargeback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chargeback_id', models.CharField(max_length=255, unique=True)),
                ('reason', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('UNDER_REVIEW', 'Under Review'), ('EVIDENCE_SUBMITTED', 'Evidence Submitted'), ('WON', 'Won'), ('LOST', 'Lost'), ('WITHDRAWN', 'Withdrawn')], default='RECEIVED', max_length=30)),
                ('received_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('evidence_bundle', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
            ],
            options={
                'db_table': 'chargebacks',
                'ordering': ['-received_date'],
            },
        ),
    ]
