# Generated by Django 4.2.7 on 2025-11-18 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_panel', '0004_featureflag_frauddetectionrule_slo_ipblacklistentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLetterQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_group', models.CharField(max_length=255)),
                ('error_message', models.TextField()),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RETRYING', 'Retrying'), ('FAILED', 'Failed'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dlq_entries', to='events.event')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_dlq_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dead_letter_queue',
                'ordering': ['-failed_at'],
                'indexes': [models.Index(fields=['status', 'failed_at'], name='dead_letter_status_e0363b_idx'), models.Index(fields=['channel_group', 'status'], name='dead_letter_channel_e2db04_idx'), models.Index(fields=['event'], name='dead_letter_event_i_bc07ee_idx')],
            },
        ),
    ]
