# Generated by Django 4.2.7 on 2025-11-17 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_order_combined_parent_order_internal_cooking_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('RIDER_CUSTOMER', 'Rider-Customer'), ('RIDER_RESTAURANT', 'Rider-Restaurant'), ('DISPATCH', 'Dispatch'), ('GENERAL', 'General')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_auto_template', models.BooleanField(default=False)),
                ('auto_trigger', models.CharField(blank=True, max_length=50)),
                ('usage_count', models.IntegerField(default=0)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'chat_templates',
                'ordering': ['category', 'display_order'],
                'indexes': [models.Index(fields=['category', 'display_order'], name='chat_templa_categor_b6dd74_idx'), models.Index(fields=['is_auto_template', 'auto_trigger'], name='chat_templa_is_auto_39dcc9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('room_type', models.CharField(choices=[('ORDER', 'Order Chat'), ('RESTAURANT', 'Restaurant Support'), ('COURIER', 'Courier Chat'), ('SUPPORT', 'Customer Support'), ('RIDER_CUSTOMER', 'Rider-Customer Chat'), ('RIDER_RESTAURANT', 'Rider-Restaurant Chat'), ('DISPATCH', 'Dispatch Chat')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('courier', models.ForeignKey(blank=True, limit_choices_to={'role': 'DELIVERY'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courier_chat_rooms', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_chat_rooms', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='orders.order')),
                ('restaurant', models.ForeignKey(blank=True, limit_choices_to={'role': 'RESTAURANT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_chat_rooms', to=settings.AUTH_USER_MODEL)),
                ('support_agent', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ADMIN', 'SUPPORT']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_chat_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_rooms',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('FILE', 'File'), ('SYSTEM', 'System Message')], default='TEXT', max_length=20)),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaskedCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_type', models.CharField(choices=[('RIDER_CUSTOMER', 'Rider-Customer'), ('RIDER_RESTAURANT', 'Rider-Restaurant'), ('DISPATCH_RIDER', 'Dispatch-Rider')], max_length=50)),
                ('caller_masked_number', models.CharField(max_length=20)),
                ('recipient_masked_number', models.CharField(max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='INITIATED', max_length=20)),
                ('provider_call_id', models.CharField(blank=True, max_length=100)),
                ('provider_data', models.JSONField(default=dict)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masked_calls_made', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masked_calls', to='orders.order')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masked_calls_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'masked_calls',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['caller', '-started_at'], name='masked_call_caller__26728d_idx'), models.Index(fields=['recipient', '-started_at'], name='masked_call_recipie_e74c13_idx'), models.Index(fields=['order', 'call_type'], name='masked_call_order_i_cb88e0_idx'), models.Index(fields=['started_at'], name='masked_call_started_209317_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['customer', 'is_active'], name='chat_rooms_custome_077b44_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['order', 'room_type'], name='chat_rooms_order_i_e6d6b2_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['last_message_at'], name='chat_rooms_last_me_a06a9d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('order', 'room_type')},
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', '-created_at'], name='chat_messag_room_id_584819_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', '-created_at'], name='chat_messag_sender__5f8b49_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['is_read'], name='chat_messag_is_read_6e9c3b_idx'),
        ),
    ]
