# Generated by Django 4.2.7 on 2025-11-16 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurantalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_wallet_wallettransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('cycle_start', models.DateTimeField()),
                ('cycle_end', models.DateTimeField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('packaging_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_fee_share', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payout_reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'settlement_cycles',
                'ordering': ['-cycle_end'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('report_type', models.CharField(default='MONTHLY', max_length=50)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_orders', models.IntegerField(default=0)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_refunds', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discrepancies', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_reports', to='restaurants.restaurant')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_reports', to='payments.settlementcycle')),
            ],
            options={
                'db_table': 'reconciliation_reports',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('bank_ifsc_code', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('account_holder_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INITIATED', 'Initiated'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20)),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('utr_number', models.CharField(blank=True, max_length=100)),
                ('failure_reason', models.TextField(blank=True)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='restaurants.restaurant')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='payments.settlementcycle')),
            ],
            options={
                'db_table': 'payouts',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='settlementcycle',
            index=models.Index(fields=['restaurant', 'status'], name='settlement__restaur_fc14d8_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementcycle',
            index=models.Index(fields=['cycle_start', 'cycle_end'], name='settlement__cycle_s_50abeb_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementcycle',
            index=models.Index(fields=['status'], name='settlement__status_1e757f_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationreport',
            index=models.Index(fields=['restaurant', 'period_start', 'period_end'], name='reconciliat_restaur_310a75_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationreport',
            index=models.Index(fields=['settlement'], name='reconciliat_settlem_7d185f_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['restaurant', 'status'], name='payouts_restaur_cc0eea_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['settlement'], name='payouts_settlem_716604_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status', 'initiated_at'], name='payouts_status_53bd7d_idx'),
        ),
    ]
